// gestor-enlaces-angular/src/app/components/link-detail/link-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { LinkService } from '../../services/link.service';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-link-detail',
  standalone: true,
  imports: [CommonModule, FormsModule], // ✅ Agregamos FormsModule y CommonModule
  templateUrl: './link-detail.component.html',
})
export class LinkDetailComponent implements OnInit {
  link: any;
  id: string = '';
  newComment: string = '';

  constructor(private route: ActivatedRoute, private linkService: LinkService) {}

  ngOnInit() {
    this.route.params.subscribe(params => {
      this.id = params['id'];
      this.loadLink();
    });
  }
  

  loadLink() {
    this.linkService.getLinkById(this.id).subscribe(
      (data) => {
        this.link = data;
      },
      (error) => {
        console.error('Error al cargar el enlace:', error);
      }
    );
  }

  vote(value: number) {
    if (!this.id) return;

    this.linkService.voteLink(this.id, value).subscribe(
      (updatedLink) => {
        this.link.votes = updatedLink.votes;
      },
      (error) => {
        console.error('Error al votar:', error);
      }
    );
  }

  addComment() {
    if (!this.newComment.trim()) return;
  
    this.linkService.addComment(this.id, this.newComment).subscribe(
      (updatedLink) => {
        this.link.comments = updatedLink.comments;
        this.newComment = ''; // Limpiar el campo después de agregar el comentario
      },
      (error) => {
        console.error('Error al agregar el comentario:', error);
      }
    );
  }
  
}

<h1>{{ link?.title }}</h1>
<p><a [href]="link?.url" target="_blank">{{ link?.url }}</a></p>
<p>Votos: {{ link?.votes }}</p>
<button (click)="vote(1)">Upvote +1</button>
<button (click)="vote(-1)">Downvote -1</button>

<h2>Comentarios ({{ link?.comments?.length }})</h2>

<!-- Mostrar comentarios anteriores -->
<div *ngFor="let comment of link?.comments">
  <p>- {{ comment }}</p>
</div>

<!-- Formulario para agregar un nuevo comentario -->
<textarea [(ngModel)]="newComment" placeholder="Nuevo comentario"></textarea>
<button (click)="addComment()">Agregar comentario</button>

// react-links/src/components/LinkDetail.jsx
import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import axios from "axios";

export default function LinkDetail() {
  const { id } = useParams();
  const [link, setLink] = useState(null);
  const [newComment, setNewComment] = useState("");

  useEffect(() => {
    axios.get(`http://localhost:3000/links/${id}`)
      .then((response) => setLink(response.data))
      .catch((error) => console.error("Error al cargar el enlace:", error));
  }, [id]);

  const vote = async (value) => {
    try {
      const response = await axios.post(`http://localhost:3000/links/${id}/votes`, { value });
      setLink({ ...link, votes: response.data.votes });
    } catch (error) {
      console.error("Error al votar:", error);
    }
  };

  const addComment = async () => {
    if (!newComment.trim()) return;
    try {
      const response = await axios.post(`http://localhost:3000/links/${id}/comments`, { comment: newComment });
      setLink({ ...link, comments: response.data.comments });
      setNewComment("");
    } catch (error) {
      console.error("Error al agregar comentario:", error);
    }
  };

  if (!link) return <h2>Cargando enlace...</h2>;

  return (
    <div>
      <h2>{link.title}</h2>
      <p><strong>URL:</strong> <a href={link.url} target="_blank" rel="noopener noreferrer">{link.url}</a></p>
      <p><strong>Etiquetas:</strong> {link.tags.join(", ")}</p>
      <p><strong>Votos:</strong> {link.votes}</p>
      <button onClick={() => vote(1)}>Upvote</button>
      <button onClick={() => vote(-1)}>Downvote</button>

      <h3>Comentarios</h3>
      <ul>
        {link.comments.map((comment, index) => (
          <li key={index}>{comment}</li>
        ))}
      </ul>

      <textarea value={newComment} onChange={(e) => setNewComment(e.target.value)} />
      <button onClick={addComment}>Agregar comentario</button>
    </div>
  );
}
